version: '{build}'
platform:
  - x64
image:
  - Visual Studio 2017
  - Ubuntu
build_script:
  - cmd: msbuild .\update\build\win32\update.vcxproj
  - cmd: msbuild .\standalone\build\win32\Tracy.vcxproj
  - cmd: msbuild .\capture\build\win32\capture.vcxproj
  - sh: sudo apt-get update && sudo apt-get -y install libglfw3-dev libgtk2.0-dev
  - sh: make -C update/build/unix debug release
  - sh: make -C standalone/build/unix debug release
  - sh: make -C capture/build/unix debug release
test: off
